### ISSUE TITLE
Scrollbar in list of values?

### ISSUE THREAD

**Issue by RadekHavelka** [bluzky/nice-select2#64]
Hello, is it possible to display scrollbar in dropdown list? I find it very un-intuitive if there are more values than visible and no scrollbar to indicate so. But any tries to set overflow to scroll failed, scrollbar is never showing up. What am I doing wrong? 

Thank you

**Comment by nikodimka** [comment]
you can try this

```css
/* Firefox */
.nice-select {
    scrollbar-width: thin;
    scrollbar-color: #D1D1D1 #EBEBEB;
}

/* Chrome, Edge and Safari */
.nice-select .list::-webkit-scrollbar {
    height: 10px;
    width: 10px;
}
.nice-select .list::-webkit-scrollbar-track {
    border-radius: 5px;
    background-color: #EBEBEB;
}

.nice-select .list::-webkit-scrollbar-track:hover {
    background-color: #dddddd;
}

.nice-select .list::-webkit-scrollbar-track:active {
    background-color: #dddddd;
}

.nice-select .list::-webkit-scrollbar-thumb {
  border-radius: 5px;
  background-color: #D1D1D1;
}

.nice-select .list::-webkit-scrollbar-thumb:hover {
  background-color: #afafaf;
}

.nice-select .list::-webkit-scrollbar-thumb:active {
  background-color: #afafaf;
}
```
