### ISSUE TITLE
overflow text

### ISSUE THREAD

**Issue by ajrulrn** [bluzky/nice-select2#68]
if have an option with a long text
the display will be like this 

![image](https://github.com/bluzky/nice-select2/assets/50063588/5303ca3a-8ed6-4729-9fb2-774d0611e1a1)

**Comment by onebitrocket** [comment]
try adding the following css to these classes.


```css
.nice-select {
   max-width: 100%;
   
   /* added just in case */
   width: 100%; 
}
.nice-select .current,
.nice-select .multiple-options {
    display: block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    
    /* added just in case */
    max-width: 100%;
}
```
